output_root: '../'

# REQUIRED for CHAOS dataset
pytorch_data_dir: '/content/drive/MyDrive/STEGO/src/pytorch_data_dir'

# Your trained CHAOS checkpoint (IMPORTANT)
model_path: "/content/drive/MyDrive/STEGO/checkpoints/chaos/chaos_chaos_date_Apr13_15-33-24/epoch=1-step=900.ckpt"

experiment_name: "chaos_demo"

res: 224          # match training resolution
batch_size: 8
num_workers: 2

use_ddp: False

hydra:
  run:
    dir: "."
  output_subdir: ~